name: GitHub Actions Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # รันบนเครื่อง Ubuntu จำลอง

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Test Script
        run: echo "Testing complete! Ready for deployment."
